code --install-extension bierner.markdown-preview-github-styles --force &
code --install-extension castwide.solargraph --force &
code --install-extension cotto.theme-harmonic16-light --force &
code --install-extension crystal-lang-tools.crystal-lang --force &
code --install-extension dbaeumer.vscode-eslint --force &
code --install-extension denoland.vscode-deno --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension formulahendry.auto-rename-tag --force &
code --install-extension golang.go --force &
code --install-extension hashicorp.terraform --force &
code --install-extension JakeBecker.elixir-ls --force &
code --install-extension jcbuisson.vue --force &
code --install-extension kaiwood.endwise --force &
code --install-extension matklad.rust-analyzer --force &
code --install-extension ms-vsliveshare.vsliveshare --force &
code --install-extension naumovs.color-highlight --force &
code --install-extension nmsmith89.incrementor --force &
code --install-extension oderwat.indent-rainbow --force &
code --install-extension rebornix.ruby --force &
code --install-extension soutaro.steep-vscode --force &
code --install-extension stkb.rewrap --force &
code --install-extension svelte.svelte-vscode --force &
code --install-extension TabNine.tabnine-vscode --force &
code --install-extension teabyii.ayu --force &
code --install-extension team-sapling.sapling --force &
code --install-extension tiehuis.zig --force &
code --install-extension Tyriar.lorem-ipsum --force &
code --install-extension vadimcn.vscode-lldb --force &
code --install-extension wingrunr21.vscode-ruby --force
