runtime! autoload/pathogen.vim
if exists('g:loaded_pathogen')
  call pathogen#infect(expand('~/.vimbundles/{}'))
endif

syntax on
filetype plugin indent on

set visualbell

set wildmenu
set wildmode=list:longest,full

set splitright
set splitbelow

set hidden

set guifont=Monaco:h16
set guioptions-=T guioptions-=e guioptions-=L guioptions-=r
set shell=bash

augroup vimrc
  autocmd!
  autocmd GuiEnter * set columns=120 lines=70 number
augroup END

" easy out for git_diff_wrapper
map Q :qa

" sourcing .vimrc.local should ALWAYS BE LAST
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif
